name: MOJ
options:
  deploymentTarget:
    iOS: "26.0"
    visionOS: "26.0"
    macOS: "26.0"

packages:
  MarkdownUI:
    url: https://github.com/gonzalezreal/swift-markdown-ui
    majorVersion: 2.4.1
  CodeEditor:
    url: https://github.com/ssig33/CodeEditor.git
    branch: develop

schemes:
  MyOwnJournal:
    build:
      targets:
        MyApp: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - MyAppTests
    archive:
      config: Release
  MyOwnJournal-Vision:
    build:
      targets:
        Journal-Vision: all
    run:
      config: Debug
    archive:
      config: Release
  MyOwnJournal-macOS:
    build:
      targets:
        JournalMac: all
    run:
      config: Release
    test:
      config: Debug
      targets:
        - MyAppTests
    archive:
      config: Release

targets:
  MyApp:
    platform: iOS
    type: application
    sources:
      - Sources/Shared
      - Sources/iOS
      - Resources
    dependencies:
      - package: MarkdownUI
      - package: CodeEditor
    settings:
      DEVELOPMENT_TEAM: QXF7ZWFA28
      GENERATE_INFOPLIST_FILE: true
      CURRENT_PROJECT_VERSION: 1
      MARKETING_VERSION: "0.0.1α"
      PRODUCT_BUNDLE_IDENTIFIER: com.ssig33.MyOwnJournal
      INFOPLIST_KEY_UILaunchScreen_Generation: true
      INFOPLIST_KEY_CFBundleDisplayName: Journal
  MyAppTests:
    platform: iOS
    type: bundle.unit-test
    sources:
      - Tests
    dependencies:
      - target: MyApp
    settings:
      DEVELOPMENT_TEAM: QXF7ZWFA28
      GENERATE_INFOPLIST_FILE: true
      PRODUCT_BUNDLE_IDENTIFIER: com.ssig33.MyOwnJournal.Tests
  Journal-Vision:
    platform: visionOS
    type: application
    sources:
      - Sources/Shared
      - Sources/vision
      - Resources
    dependencies:
      - package: MarkdownUI
    settings:
      DEVELOPMENT_TEAM: QXF7ZWFA28
      GENERATE_INFOPLIST_FILE: true
      CURRENT_PROJECT_VERSION: 1
      MARKETING_VERSION: "0.0.1α"
      PRODUCT_BUNDLE_IDENTIFIER: com.ssig33.MyOwnJournal
      INFOPLIST_KEY_UILaunchScreen_Generation: true
      INFOPLIST_KEY_CFBundleDisplayName: Journal
      ASSETCATALOG_COMPILER_APPICON_NAME: VisionIcon
    info:
      path: Info.plist
      properties:
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
  JournalMac:
    platform: macOS
    type: application
    sources:
      - Sources/Shared
      - Sources/macOS
      - Resources
    dependencies:
      - package: MarkdownUI
      - package: CodeEditor
    settings:
      DEVELOPMENT_TEAM: QXF7ZWFA28
      GENERATE_INFOPLIST_FILE: true
      CURRENT_PROJECT_VERSION: 1
      MARKETING_VERSION: "0.0.1α"
      PRODUCT_BUNDLE_IDENTIFIER: com.ssig33.MyOwnJournal
      ASSETCATALOG_COMPILER_APPICON_NAME: macIcon
      INFOPLIST_KEY_CFBundleDisplayName: Journal


